---
- name: Deploy PHP project
  hosts: testserver
  become: yes

  tasks:
    - name: Copy project files
      copy:
        src: ../project/
        dest: /var/www/html/project/
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Restart apache
      service:
        name: apache2
        state: restarted
