---
- name: Configure test server
  hosts: testserver
  become: yes

  tasks:
    - name: Install Apache and PHP
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-cli
          - php-mbstring
          - php-xml
          - php-zip
        state: present
        update_cache: yes

    - name: Enable Apache mods
      command: a2enmod php*

    - name: Create virtual host
      template:
        src: vhost.tpl
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Restart apache
      service:
        name: apache2
        state: restarted
