services:

  ssh-agent:
    build:
      context: .
      dockerfile: Dockerfile.ssh_agent
    container_name: ssh-agent
    volumes:
      - ./project:/home/jenkins/project
      - ./jenkins_ssh_agent:/home/jenkins/.ssh/id_rsa
    tty: true


  ansible-agent:
    build:
      context: .
      dockerfile: Dockerfile.ansible_agent
    container_name: ansible-agent
    volumes:
      - ./:/home/ansible/project
      - ./ansible_to_testserver:/home/ansible/.ssh/test_server_key
    tty: true

  test-server:
    build:
      context: .
      dockerfile: Dockerfile.test_server
    container_name: test-server
    ports:
      - "2222:22"
      - "8081:80"

  jenkins-controller:
    image: jenkins/jenkins:lts
    container_name: jenkins-controller
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=https://jenkins.io
volumes:
  jenkins_home: