FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
      python3 \
      python3-pip \
      sshpass \
      openssh-client \
      openssh-server \
      git \
      sudo && \
    pip3 install ansible && \
    useradd -ms /bin/bash jenkins && \
    echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    mkdir -p /home/jenkins/.ssh && \
    mkdir -p /var/run/sshd && \
    chown -R jenkins:jenkins /home/jenkins/.ssh && \
    chmod 700 /home/jenkins/.ssh

EXPOSE 22

USER root
WORKDIR /home/jenkins

CMD ["/usr/sbin/sshd", "-D"]
