FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    openssh-client \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash jenkins

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN chown -R jenkins:jenkins /home/jenkins

USER jenkins
WORKDIR /home/jenkins

RUN mkdir -p /home/jenkins/.ssh

CMD ["sleep", "infinity"]
